#include "stdafx.h"

DECLARE_COMPONENT_VERSION(
	COMPONENT_TITLE,
	COMPONENT_VERSION,
	"Build: " __TIME__ ", " __DATE__ "\n"
	"Copyright (C) 2009-2012 Dremora\n"
	"Copyright (C) 2015-2019 marc2003"
);

VALIDATE_COMPONENT_FILENAME(COMPONENT_DLL_NAME);
